version: "3.7"
services:

  # Snapshot hub
  snapshot-hub:
    build: .
    container_name: snapshot-hub
    env_file:
      - .env.local
    depends_on:
      - snapshot-redis
    ports:
      - "8080:8080"

  # Snapshot Redis instance
  snapshot-redis:
    image: redis:6.0
    container_name: snapshot-redis

  # Snapshot MySQL instance
  snapshot-mysql:
    image: mysql:8.0.21
    container_name: snapshot-mysql
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "testdb"

networks:
  default:
    name: snapshot-network
